### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nbs**

### CODE REVIEW

**Comment by frankdejonge** [comment]
Please use <em> instead of <i> and supply a 'type' section in the params section. For an example look at the mongo_db docs or the Query Builder docs. Thanks

**Comment by nbs** [comment]
I changed ALL the italicized to emphasis tags, and added a type.  Though, wouldn't $encoding be mixed because it can be either string or boolean?  I just put string, since boolean is only the default, but it could take both.

**Comment by nbs** [comment]
I just meant to hit 'comment' not 'comment & close'...

**Comment by frankdejonge** [comment]
Sorry to be so picky, but the default value will have this format <pre class="php"><code>value</code></pre>

**Comment by nbs** [comment]
The default values?  I don't see that on any other method's default values.

**Comment by frankdejonge** [comment]
oh I see the comments didn't show the markup, I'll merge and fix it afterwards

**Pull request merged**
