### PR TITLE
Added note to Lang class about the Config::set method

### PR DESCRIPTION
**Pull request by zoe-edwards**
It’s not obvious straight away that one uses the Config class to control the language. Also added a note about the existence of the default language.

### CODE REVIEW

**Comment by zoe-edwards** [comment]
(Thought I’d use Welsh as an example!)

**Comment by WanWizard** [comment]
Please make the links relative to the current directory, not to the docroot. 
And the anchor shouldn't be prefixed with a slash.

**Comment by zoe-edwards** [comment]
Sorted.

**Comment by WanWizard** [comment]
Not really.

config.html is in the same folder as lang.html, so it should be "./config.html".

**Comment by zoe-edwards** [comment]
Good point! Try now...

**Comment by WanWizard** [comment]
You still missed my initial remark about the anchor.

"./config.html#/method_set" should be "./config.html#method_set" (no slash)

**Comment by zoe-edwards** [comment]
I would like to take this opportunity to point out that I do actually do this for a living, but I’m just very tired.

**Comment by WanWizard** [comment]
:-)

**Pull request merged**
