### PR TITLE
Added a cookie to remember the main menu open/close state when loading a...

### PR DESCRIPTION
**Pull request by chris-roerig**
... new page

### CODE REVIEW

**Comment by WanWizard** [comment]
Can this be implemented another way?

Now, if you load a page with an anchor (to jump to a specific topic in the page), the code makes it jump back to the top of the page to re-open the main menu. Very irritating, and it impacts the usability of the docs.

We need to release 1.6 soon, so if this isn't fixed, I'll revert this PR.

**Comment by chris-roerig** [comment]
I won't have a fix until tomorrow am. Do what you must. Thanks

**Comment by WanWizard** [comment]
No problem, I'm aiming for end of the week for the release.

**Comment by frankdejonge** [comment]
@WanWizard fixed this! Fixing a last quirk :)

**Comment by WanWizard** [comment]
Cool, thanks!

**Pull request merged**
