### PR TITLE
Modify a misprint about orm\model::to_array()

### PR DESCRIPTION
**Pull request by niaeashes**
Modify a misprint about orm\model::to_array(), from $_to_array_filter to $_to_array_exclude in an example code.

### CODE REVIEW

**Comment by WanWizard** [comment]
This has already be corrected. 

When you spot something like this, please check http://dev-docs.fuelphp.com to see if it's already fixed.

We don't accept changes on master branches, only on the latest develop branch.

**Comment by niaeashes** [comment]
Thanks you for your answer.

But it's yet fixed at http://fuelphp.com/docs/packages/orm/creating_models.html

Why don't update?

**Comment by frankdejonge** [comment]
This is because of the release strategy. The main docs are updated per release. The dev-docs are there so people can see the latests fixes reflected.

**Comment by niaeashes** [comment]
I see that. Thank you for your response.

**Pull request closed without merging**
