### PR TITLE
Update documents to follow latest Model structure to use Model as namespace

### PR DESCRIPTION
**Pull request by crynobone**
As used in Model_Crud, Orm\Model documents should follow the same structure (use Model as namespace instead of Model_ prefix)

### CODE REVIEW

**Comment by philsturgeon** [comment]
When did we change this?!

**Comment by crynobone** [comment]
Earliest code should be from https://github.com/fuel/oil/commit/6bf5ffdbc779f0a1ef31c907f6aac4330b628e37

**Comment by frankdejonge** [comment]
@philsturgeon both ways are supported (Model_Somethin and Model\Something), but you probably already knew that. I reckon @dhorrigan used this to get people familiar with the posibility. I think it's great that it's supported. But maybe we should not introduce this like this in the current version. All the other classes don't follow this pattern, so it might get a little confusing.

**Comment by philsturgeon** [comment]
I missed this, I was too pissed off with him randomly rewriting me generation logic to spot the `namespace Model;`. What the hell? We have a wonderful, logical CSF system and now we're breaking things up into random namespaces... for what?

We've talked about this so many times @dhorrigan and it has gone in and out and in and OUT. We always end up taking it back out, because it is pointless.

If you can prove this is not a namespace for the sake of a namespace then yay, but why is it here and why is it in v1.1?

**Comment by dhrrgn** [comment]
I did it because it is nicer.  It is piss annoying to have to write: `Model_User::find_by_email()` (or similar) over and over again.  So if it is in the Model namespace you can just do `use Model\User;` at the top of your file then just user `User::find_by_email()`.  No need to keep writing Model_ over and over again.

**Comment by frankdejonge** [comment]
I agree with @dhorrigan on it being nicer and quicker to write stuff. IMO it's not a namespace because of the namespace, it's actually something that adds a speed advantage in writing the rest of your stuff. Side effect is also that the use of namespaces is promoted, which isn't a bad thing per se.

**Comment by philsturgeon** [comment]
Understood but why would we have this one for Model and nothing else?

We can have any level of classes in there, includkng Observer_, Auth_ Foo_ and these are all mapped to their location based on the same rule, _ = /.

If we do this for Model then we are breaking the convention purely for the sake of making things look a tiny tiny tiny bit better.

People can use User::find() if they want, just don't put it in the model folder. This is not a change that we need at all, and even if you guys are adamant it 100% has to be in there, it should not be put in by default and therefore not written by Oil.

**Pull request closed without merging**
