### PR TITLE
Grammar fix. Removal of underscore between always_load.

### PR DESCRIPTION
**Pull request by albertvolkman**
Small issue I saw... I hope to start committing more as I find them!

### CODE REVIEW

**Comment by jschreuder** [comment]
Actually that was on purpose to signify it refers to a key in the config file, should probably be put in code-tags though - I'll do that myself.

**Comment by albertvolkman** [comment]
Ah gotcha. I'm still pretty fresh with FuelPHP, but excited to start using it regularly :)

**Comment by frankdejonge** [comment]
@jschreuder: I was going to put that in after the merge. Already merged.

**Comment by jschreuder** [comment]
@FrenkyNet when I say "I'll do that" it's not all that usefull to start doing the same thing.

**Comment by frankdejonge** [comment]
@jschreuder: Sorry, missed that! I added it like this: https://github.com/fuel/docs/commit/ac3e23c78d84dc0d8a3017cfea1cadd21f906507 change if you'd like it differently.

**Pull request merged**
