### PR TITLE
Added configuration section to the Format class

### PR DESCRIPTION
**Pull request by billmn**

### CODE REVIEW

**Comment by WanWizard** [comment]
Why the new parameters? Is this for a specific Uploadify version? If so, maybe add the version as a comment.

**Comment by billmn** [comment]
Is for the new version of Uploadify .... the old parameters are no longer supported.

Would you mantain the old parameters?

http://www.uploadify.com/documentation/

**Comment by WanWizard** [comment]
No, I would suggest the docs specifies that these parameters are for Uploadify version x.

**Comment by billmn** [comment]
ok mate!

**Pull request merged**
