### PR TITLE
Changed text to blob type of profile_fields in simpleauth

### PR DESCRIPTION
**Pull request by SCIF**
According to [php docs](http://php.net/manual/en/function.serialize.php#refsect1-function.serialize-returnvalues) changed field type to avoid data losing.

Data losing reported by [Maxlab](https://github.com/Maxlab)

### CODE REVIEW

**Comment by huglester** [comment]
what data are you trying to store? I think BLOB is bad idea here.

**Comment by WanWizard** [comment]
You will need a BLOB if you intend to store serialized objects. But TEXT is absolutely fine if you serialize an array that doesn't contain objects.

So I don't think this should have changed by default to BLOB, but perhaps a note is handy to point this out. Same is true btw for sessions, as they are serialized as well.

**Comment by SCIF** [comment]
There are no restrictions in docs about data types which can be stored in sessions/profile_fields.

I don't understand why you don't want to accept this improvement. It doesn't brake anything and just improve supported data types.

**Comment by WanWizard** [comment]
With sessions I mean that session data is stored in the session table as a serialzed array too. And afaik it's defined as TEXT there too.

In the meantime I did some testing and research, and it turns out that not only serialized objects can cause binary data to be introduced. but also UTF-8 data. Which is far more likely, and in that context, blob might be a good idea.

**Comment by WanWizard** [comment]
This can no longer be merged.

**Pull request closed without merging**
