### PR TITLE
ORM - Observers : More details on difference between before_save and before_update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by WanWizard** [comment]
The same is then probably true for before_insert.

Reason for this is that before_save is dealt with in the save() method, while the other two are handled in the update() and insert() methods, which aren't called when there's nothing to update or insert.

Perhaps add that as well, for completeness.

**Comment by ghost** [comment]
I believe this note on observer events is now complete and more concise.

**Comment by WanWizard** [comment]
Can you re-submit it against 1.6/develop. 

1.5 has been released now, so we don't accept PR's on that branch anymore.

**Comment by ghost** [comment]
ok

**Pull request closed without merging**
