### PR TITLE
Update installation/tutorials.html

### PR DESCRIPTION
**Pull request by kenjis**
remove dead link, add my book.

### CODE REVIEW

**Comment by emlynwest** [comment]
I am not sure I like the idea of adding a link to buy a book. Especially when I can't review the content of said book.

**Comment by WanWizard** [comment]
Perhaps we should add a disclaimer than none of these books are endorsed by FuelPHP. Because none of them are reviewed I think...

**Comment by emlynwest** [comment]
I'd be happy with that.

**Comment by kenjis** [comment]
There is already 

> The FuelPHP development wasn't involved in writing any of these books. Ensure the quality and the contents of the book meets with your requirements and expectations before purchasing any of them. 

Do you need more?

**Comment by emlynwest** [comment]
Something along the lines of "the content of these books cannot be guaranteed to be accurate" I guess.

**Comment by kenjis** [comment]
How about contents other than Books?

**Comment by emlynwest** [comment]
Personally I have yet to find anything, which is a shame. Once v2 is out or in beta I would very much like to write some in-depth tutorials.

**Comment by WanWizard** [comment]
Maybe something more generic:

> The FuelPHP development team wasn't involved in writing any of these articles, tutorials or books. Their contents can not be guaranteed to be accurate. Please ensure the quality and the contents meets with your requirements and expectations before using any of them.

**Comment by kenjis** [comment]
Thanks! I've updated.

**Comment by emlynwest** [comment]
Works for me

**Pull request merged**
