### PR TITLE
Updated download page to current version (1.4)

### PR DESCRIPTION
**Pull request by ewen**

### CODE REVIEW

**Comment by WanWizard** [comment]
PR's are only accepted on the current develop branch.

1.5 will be released soon, we'll fix this issue then.

**Comment by kenjis** [comment]
@WanWizard "PR's are only accepted on the current develop branch." You mean about only docs? This PR is clearly a bug of 1.4 docs.

What about bugs of code in 1.4?

**Comment by WanWizard** [comment]
Stuff that can't wait on the next release is commited to the current develop branch, and cherry picked to a hotfix release of the current version. Same for docs.

As the 1.5 release is around the corner, it's pointless putting much effort into backporting to 1.4.

**Comment by kenjis** [comment]
I just want to confirm the way of doing. It's confusing. http://fuelphp.com/docs/contribute.html is not easy to understand.

Is this OK?
1. Send PR to the next release  develop branch (eg, 1.5/develop), and if it should be cherry picked to the current version (eg, 1.4), you do so.
2. Send PR to the current release develop branch (eg, 1.4/develop) if it is a bug only affected to the current version.

**Comment by WanWizard** [comment]
It's easy. PR's ALWAYS go to the current develop branch. On every repository.

If a PR fixes a bug that needs to be backported to the current master (= the release version), we will:
- cherry pick that fix into the previous develop branch (i.e. the develop branch of the release version)
- branch that to a new master (with a hotfix release number, like 1.4.1)
- create a hotfix release for that version based on that branch

There is one possible exception, which is if a critical fix is needed, but the code where that fix should be applied has been changed in the current develop so that it's no longer possible to add it, AND the changed code can not be backported. 

In that case we will apply the fix manually to the previous develop branch, and continue with points 2 and 3.

**Pull request closed without merging**
