### PR TITLE
Update download links

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks!

**Comment by kenjis** [comment]
Can you cherry-pick to 1.5/develop and 1.5/master?

Because we can't download latest zip from the official docs http://fuelphp.com/docs/installation/download.html

**Comment by WanWizard** [comment]
Done.

It might take a while before the site is updated, I think it updates only once a day.

**Comment by kenjis** [comment]
Thanks! Updated already.

**Pull request merged**
