### PR TITLE
Update installation/download.html for 1.7.2

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by sdrdis** [comment]
Hi, is this normal that it doesn't appear on the official website ?

http://fuelphp.com/docs/installation/download.html

**Comment by WanWizard** [comment]
What do you mean? Ah,  the fix above?

It isn't there because 1.7.3. should been been released by now. Something a bit delayed due to health reasons, but expect it in the next few days (providing no last-minute show-stoppers pop up).

**Comment by kenjis** [comment]
It is not good, but it is normal to FuelPHP, because release manager forgot updating the link before releasing 1.7.2, and it seems the docs on the site are never updated after it.

If @WanWizard  will forget updating the link to 1.7.3, before releasing 1.7.3. It will be out of dated for a long time.

I hope he add the task to his todo list.

**Comment by WanWizard** [comment]
One of the big questions on the table is still: what exactly should be the contents of the zip? These days, Fuel heavily depends on Composer. Is the zip meant to be a working environment, with all composer dependencies present, but no composer.json and no .git folders? Or do we expect people to run composer locally after installing the zip (in which case the fuel/fuel zip will do fine)?

**Comment by kenjis** [comment]
I think Zip file should include all composer dependencies present, and composer.json and no .git folders.
If there is no composer.json, users can't add easily composer dependency which they want.
If there is no all composer dependencies Fuel requires, Zip would not work after unzipping it.

**Comment by sdrdis** [comment]
I think it should include all dependencies already installed with the composer.json file (as it currently is). .git folders are not necessary. That way, Zip files can be used by people who are not familiar with composer or git, and just want things to work.

**Comment by kenjis** [comment]
@sdrdis Exactly.

**Comment by WanWizard** [comment]
Thought so, just checking. ;-) I'll try to sort it out a.s.a.p.

**Comment by WanWizard** [comment]
1.7.2. zip on the website is updated.

**Comment by sdrdis** [comment]
Great :), thank you very much.

**Comment by kenjis** [comment]
Thank you!

**Pull request merged**
