### PR TITLE
Fixed link, added link

### PR DESCRIPTION
**Pull request by zoe-edwards**

### CODE REVIEW

**Comment by jschreuder** [comment]
The Orm is not "the way" of creating models, as mentioned in the paragraph above the line a model is just a class like any other, using the Orm is "a way" to handle models and was already introduced at the bottom of the page. No need to add more, though something might be said for improving the heading and text about the Orm.

[edit] I removed the line and improved the text introducing the Orm. [/edit]

**Comment by zoe-edwards** [comment]
I was looking for some confirmation of how to write a model, as I’m used to CodeIgniter which extends CI_Model. Writing “anything you like” is just a tad too open for me and that bit of code on the Orm page gives one the confirmation that you don’t need that. Maybe just include a "you _can_ write your Model as such:".

**Comment by jschreuder** [comment]
I wasn't arguing against that, but the Orm is introduced on the page already just not as the first option. No need to make it look like you have to use the Orm, it's optional - and it was already expressed as such on the page.

Also: CI's CI_Model does pretty much nothing, used to do just a bit of magic to make the DB available as $this->db (and the same for all loaded libs). If memory serves me right, nowadays it's just a magic `__get()` method forwarding you to the CI superobject. There's no need for anything like that in Fuel.

**Comment by zoe-edwards** [comment]
I understand, that’s completely reasonable – I just feel that the learning curve for learning Fuel is quite steep at the moment, and these things need to be broken right down to introduce the world of MVC to people unfamiliar with it! :)

**Comment by jschreuder** [comment]
Again, not disagreeing. But also again: **it's already on the page!** If someone wants to learn they should be able to finish less than half a page, and if they're not willing to do so we don't care about them. And last but not least: an Orm isn't an easy thing to grasp when you're not familiar with the idea yet - so instead of making things easier you'd actually make it harder for a lot of beginners.

**Comment by jschreuder** [comment]
This commit should address your concerns without over emphesizing the Orm: https://github.com/fuel/docs/commit/c97c035ac31d3142518307ed1f77ac128fe16b5a

**Comment by zoe-edwards** [comment]
That’s super, sorry to hammer the point over and over, I appreciate it. I’m trying to teach the concept of models to somebody at the moment and it’s not easy, and like you say, Orm is another step which even I’m avoiding for now.

**Pull request merged**
