### PR TITLE
Added Arr::keyval_to_assoc docs

### PR DESCRIPTION
**Pull request by sagikazarmark**
I don't get this in the title:

`keyval_to_assoc($array = null, $key_field = null, $val_field = null)`

Why are those values null, when the arguments are required?

(Copy and paste from assoc_to_keyval)

### CODE REVIEW

**Comment by WanWizard** [comment]
are they null in the code? If not, then the docs are incorrect (and if they are, the code is incorrect too, since you are right, they are required).

**Comment by sagikazarmark** [comment]
No, in the code they are not null, so the docs are incorrect.

Would you like me to correct it?

**Comment by WanWizard** [comment]
Yes please. Then I can merge this.

**Comment by sagikazarmark** [comment]
Ok. But keep in mind, that this PR depends on the PR sent for core.

**Comment by WanWizard** [comment]
I'll merge that one too. ;)

**Comment by sagikazarmark** [comment]
@WanWizard docs corrected. I also found another one, so I corrected that too.

**Pull request merged**
