### PR TITLE
Fix h4 tag's attributes for Fieldset get_config method.

### PR DESCRIPTION
**Pull request by omoon**
Signed-off-by: omoon omooon@gmail.com

### CODE REVIEW

**Comment by frankdejonge** [comment]
And can you remove the `id="method_get_config"`?

**Comment by omoon** [comment]
I think `id="method_get_config"` is needed. If that is removed, you will be unable to jump that point when you click the link.

**Comment by frankdejonge** [comment]
As I explained in the previous pull-request, this is automatically done by the doc's javascript.

**Comment by omoon** [comment]
https://github.com/fuel/docs/blob/1.4/develop/assets/js/combined.js#L179

I think this line handles this action, and it seems that it needs 'id' attribute to create the href value.
`<a href="#/'+$(this).attr('id')+'">`

I tried to remove that attribute, I got the link like.. `<a href="#/undefined">Fieldset::get_config()</a>`.

**Comment by WanWizard** [comment]
The 'id' is indeed needed for the method popup to work.

**Pull request merged**
